### ISSUE TITLE
Can not share current directory on host with the container using bind mount

### ISSUE THREAD

**Issue by zeljkofilipin** [zeljkofilipin/filipin.eu#3]
I can build an image.

```
~/Documents/github/zeljkofilipin/filipin.eu$ docker build --tag blog:1.1 .Sending build context to Docker daemon  43.36MB
Step 1/8 : FROM ruby:2.7
 ---> cd155aa807df
Step 2/8 : RUN bundle config --global frozen 1
 ---> Using cache
 ---> 6529d7c843d9
Step 3/8 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 2f3cd053235f
Step 4/8 : COPY Gemfile Gemfile.lock ./
 ---> Using cache
 ---> f26fe6fee994
Step 5/8 : RUN bundle install
 ---> Using cache
 ---> f8c41512acad
Step 6/8 : EXPOSE 4000 35729
 ---> Running in 1f16f063cb69
Removing intermediate container 1f16f063cb69
 ---> 39f011cf0057
Step 7/8 : COPY . .
 ---> 1eb81d1cca1b
Step 8/8 : CMD ["bundle", "exec", "jekyll", "serve", "--host", "0.0.0.0", "--drafts", "--livereload"]
 ---> Running in 972261609c8f
Removing intermediate container 972261609c8f
 ---> 7cae174c1199
Successfully built 7cae174c1199
Successfully tagged blog:1.1
```

I can run an container, sharing current directory on the host with the container.

```
~/Documents/github/zeljkofilipin/filipin.eu$ docker run --publish 4000:4000 --publish 35729:35729 --name blog-1.1.0 --mount type=bind,source="$(pwd)",target=/usr/src/app blog:1.1
Configuration file: /usr/src/app/_config.yml
            Source: /usr/src/app
       Destination: /usr/src/app/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
                    done in 12.411 seconds.
 Auto-regeneration: enabled for '/usr/src/app'
LiveReload address: http://0.0.0.0:35729
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
        LiveReload: Browser connected
```

I'm trying to do the same thing using docker-compose. When `docker-compose.yml` doesn't have `volumes`...

```
version: "3.8"
services:
  web:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
```

... everything runs fine, but the folder on the host is not shared with the container.

```
~/Documents/github/zeljkofilipin/filipin.eu$ docker-compose up  
Creating network "filipineu_default" with the default driver
Creating filipineu_web_1 ... done
Attaching to filipineu_web_1
web_1  | Configuration file: /usr/src/app/_config.yml
web_1  |             Source: /usr/src/app
web_1  |        Destination: /usr/src/app/_site
web_1  |  Incremental build: disabled. Enable with --incremental
web_1  |       Generating... 
web_1  |        Jekyll Feed: Generating feed for posts
web_1  |                     done in 4.343 seconds.
web_1  |  Auto-regeneration: enabled for '/usr/src/app'
web_1  | LiveReload address: http://0.0.0.0:35729
web_1  |     Server address: http://0.0.0.0:4000/
web_1  |   Server running... press ctrl-c to stop.
web_1  |         LiveReload: Browser connected
```

When I add `volumes` to `docker-compose.yml`...

```
version: "3.8"
services:
  web:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - type: bind
        source: ./
        target: /usr/src/ap
```

... I get

```
~/Documents/github/zeljkofilipin/filipin.eu$ docker-compose up
Starting filipineu_web_1 ... done
Attaching to filipineu_web_1
web_1  | bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
web_1  | Bundler::GemNotFound: Could not find listen-3.3.3 in any of the sources
web_1  |   /usr/local/lib/ruby/2.7.0/bundler/spec_set.rb:86:in `block in materialize'
web_1  |   /usr/local/lib/ruby/2.7.0/bundler/spec_set.rb:80:in `map!'
web_1  |   /usr/local/lib/ruby/2.7.0/bundler/spec_set.rb:80:in `materialize'
web_1  |   /usr/local/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
web_1  |   /usr/local/lib/ruby/2.7.0/bundler/definition.rb:237:in `specs_for'
web_1  |   /usr/local/lib/ruby/2.7.0/bundler/definition.rb:226:in `requested_specs'
web_1  |   /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:101:in `block in definition_method'
web_1  |   /usr/local/lib/ruby/2.7.0/bundler/runtime.rb:20:in `setup'
web_1  |   /usr/local/lib/ruby/2.7.0/bundler.rb:149:in `setup'
web_1  |   /usr/local/lib/ruby/2.7.0/bundler/setup.rb:20:in `block in <top (required)>'
web_1  |   /usr/local/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
web_1  |   /usr/local/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
web_1  |   /usr/local/lib/ruby/2.7.0/bundler/setup.rb:20:in `<top (required)>'
filipineu_web_1 exited with code 1
```

Documentation I've read:

- https://docs.docker.com/storage/bind-mounts/#start-a-container-with-a-bind-mount
- https://docs.docker.com/compose/compose-file/#long-syntax-3
- https://docs.docker.com/get-started/nodejs/develop/#use-compose-to-develop-locally

**Comment by zeljkofilipin** [comment]
Won't fix.
